Collections:
  - Name: LRASPP
    Metadata:
      Training Data:
        - Cityscapes

Models:

  - Name: lraspp_m-v3-d8_512x1024_320k_cityscapes
    In Collection: LRASPP
    Metadata:
      inference time (fps): 15.22
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 69.54
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v3/lraspp_m-v3-d8_512x1024_320k_cityscapes/lraspp_m-v3-d8_512x1024_320k_cityscapes_20201224_220337-cfe8fb07.pth
    Config: configs/lraspp/lraspp_m-v3-d8_512x1024_320k_cityscapes.py



  - Name: lraspp_m-v3-d8_scratch_512x1024_320k_cityscapes
    In Collection: LRASPP
    Metadata:
      inference time (fps): 14.77
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 67.87
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v3/lraspp_m-v3-d8_scratch_512x1024_320k_cityscapes/lraspp_m-v3-d8_scratch_512x1024_320k_cityscapes_20201224_220337-9f29cd72.pth
    Config: configs/lraspp/lraspp_m-v3-d8_scratch_512x1024_320k_cityscapes.py



  - Name: lraspp_m-v3s-d8_512x1024_320k_cityscapes
    In Collection: LRASPP
    Metadata:
      inference time (fps): 23.64
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 64.11
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v3/lraspp_m-v3s-d8_512x1024_320k_cityscapes/lraspp_m-v3s-d8_512x1024_320k_cityscapes_20201224_223935-61565b34.pth
    Config: configs/lraspp/lraspp_m-v3s-d8_512x1024_320k_cityscapes.py



  - Name: lraspp_m-v3s-d8_scratch_512x1024_320k_cityscapes
    In Collection: LRASPP
    Metadata:
      inference time (fps): 24.50
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 62.74
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v3/lraspp_m-v3s-d8_scratch_512x1024_320k_cityscapes/lraspp_m-v3s-d8_scratch_512x1024_320k_cityscapes_20201224_223935-03daeabb.pth
    Config: configs/lraspp/lraspp_m-v3s-d8_scratch_512x1024_320k_cityscapes.py
